"use strict";

exports.__esModule = true;
exports.CURRENT_MONTH_FORMAT = exports.COMMON_FORMAT = void 0;
var COMMON_FORMAT = 'YYYY-MM-DD';
exports.COMMON_FORMAT = COMMON_FORMAT;
var CURRENT_MONTH_FORMAT = 'MMMM YYYY';
exports.CURRENT_MONTH_FORMAT = CURRENT_MONTH_FORMAT;